version: "3"
services:
    app:
        build:
            context: './docker/php/8.3'
            dockerfile: Dockerfile
            args:
                USERNAME: '${USERNAME:-www-data}'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        env_file:
            - .env
        volumes:
            - '.:/var/www/html'
            - './docker/logs/supervisor:/var/log/supervisor'
        networks:
            - rss
        depends_on:
            mysql:
                condition: service_healthy
    #            - redis
    #            - meilisearch
    #            - mailpit
    #            - selenium
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 0
        volumes:
            - './docker/mysql/data:/var/lib/mysql'
            - './docker/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - rss
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
#    redis:
#        image: 'redis:alpine'
#        ports:
#            - '${FORWARD_REDIS_PORT:-6379}:6379'
#        volumes:
#            - 'rss-redis:/data'
#        networks:
#            - rss
#        healthcheck:
#            test:
#                - CMD
#                - redis-cli
#                - ping
#            retries: 3
#            timeout: 5s
#    meilisearch:
#        image: 'getmeili/meilisearch:latest'
#        ports:
#            - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
#        environment:
#            MEILI_NO_ANALYTICS: '${MEILISEARCH_NO_ANALYTICS:-false}'
#        volumes:
#            - 'rss-meilisearch:/meili_data'
#        networks:
#            - rss
#        healthcheck:
#            test:
#                - CMD
#                - wget
#                - '--no-verbose'
#                - '--spider'
#                - 'http://127.0.0.1:7700/health'
#            retries: 3
#            timeout: 5s
#    mailpit:
#        image: 'axllent/mailpit:latest'
#        ports:
#            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
#            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
#        networks:
#            - rss
#    selenium:
#        image: selenium/standalone-chromium
#        extra_hosts:
#            - 'host.docker.internal:host-gateway'
#        volumes:
#            - '/dev/shm:/dev/shm'
#        networks:
#            - rss
networks:
    rss:
        driver: bridge
volumes:
    rss-mysql:
        driver: local
#    rss-redis:
#        driver: local
#    rss-meilisearch:
#        driver: local
